# Generated by Django 3.1.2 on 2020-10-08 18:43

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201008_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cropperjs.models.CropperImageField(null=True, upload_to=''),
        ),
    ]
