# Generated by Django 3.1.2 on 2020-10-10 19:14

import cropperjs.models
from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20201008_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio='1.0', blank=True, dimensions=(75, 75), null=True, upload_to=recipe.models._recipe_upload_to),
        ),
    ]
