# Generated by Django 3.1.2 on 2020-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201010_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
